### ISSUE TITLE
Running the project

### ISSUE THREAD

**Issue by faiyaz26** [FatalEagle/Judge#1]
Hello, I have cloned this project and build it on CodeBlocks. And it seems it requires some command line argument. If it is possible, can you let me know about those arguments ?

**Comment by FatalEagle** [comment]
This is a needlessly complicated and specialized judge, so you probably don't want to use this (the code is pretty bad too).

Just to satisfy your curiosity, the command line arguments for some version (not necessarily the current version on Github) are

filename problem_number problem_name start_case_number end_case_number initial_point_value 
program_files_path, cpp_compiler_path, java_compiler_path

and the directory structure required to run the judge is also complicated and weird. This judge is pretty obsolete though, and has been superseded by [the DMOJ judge](https://github.com/DMOJ/judge).
